import { z } from "zod";
import { MethodDef, BooleanFlag, ANNOTATIONS } from "../method-registry.js";

export const botMethods: MethodDef[] = [
  {
    apiMethod: "getMe",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_me",
    description: "Get basic information about the bot (id, name, username, etc).",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "User",
    params: [],
  },
  {
    annotations: ANNOTATIONS.modify,
    apiMethod: "logOut",
    toolName: "log_out",
    description: "Log out from the cloud Bot API server. Use before moving to a local server.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [],
  },
  {
    annotations: ANNOTATIONS.modify,
    apiMethod: "close",
    toolName: "close",
    description: "Close the bot instance. Use before moving between local servers.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [],
  },
  {
    apiMethod: "setMyCommands",
    annotations: ANNOTATIONS.modify,
    toolName: "set_my_commands",
    description: "Set the bot's command list shown in the menu.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "commands", type: z.any(), required: true, description: "Array of BotCommand objects" },
      { name: "scope", type: z.any(), required: false, description: "BotCommandScope — where commands apply" },
      { name: "language_code", type: z.string(), required: false, description: "Two-letter ISO 639-1 language code" },
    ],
  },
  {
    apiMethod: "deleteMyCommands",
    annotations: ANNOTATIONS.destructive,
    toolName: "delete_my_commands",
    description: "Delete the bot's command list for a given scope and language.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "scope", type: z.any(), required: false, description: "BotCommandScope" },
      { name: "language_code", type: z.string(), required: false, description: "Language code" },
    ],
  },
  {
    apiMethod: "getMyCommands",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_my_commands",
    description: "Get the bot's current command list.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "Array of BotCommand",
    params: [
      { name: "scope", type: z.any(), required: false, description: "BotCommandScope" },
      { name: "language_code", type: z.string(), required: false, description: "Language code" },
    ],
  },
  {
    apiMethod: "setMyName",
    annotations: ANNOTATIONS.modify,
    toolName: "set_my_name",
    description: "Set the bot's name.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "name", type: z.string().max(128), required: false, description: "Bot name (0-128 chars)" },
      { name: "language_code", type: z.string(), required: false, description: "Language code" },
    ],
  },
  {
    apiMethod: "getMyName",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_my_name",
    description: "Get the bot's name for a given language.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "BotName",
    params: [
      { name: "language_code", type: z.string(), required: false, description: "Language code" },
    ],
  },
  {
    apiMethod: "setMyDescription",
    annotations: ANNOTATIONS.modify,
    toolName: "set_my_description",
    description: "Set the bot's description (shown in empty chat).",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "description", type: z.string().max(512), required: false, description: "Description (0-512 chars)" },
      { name: "language_code", type: z.string(), required: false, description: "Language code" },
    ],
  },
  {
    apiMethod: "getMyDescription",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_my_description",
    description: "Get the bot's description.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "BotDescription",
    params: [
      { name: "language_code", type: z.string(), required: false, description: "Language code" },
    ],
  },
  {
    apiMethod: "setMyShortDescription",
    annotations: ANNOTATIONS.modify,
    toolName: "set_my_short_description",
    description: "Set the bot's short description (shown on profile page).",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "short_description", type: z.string().max(120), required: false, description: "Short description (0-120 chars)" },
      { name: "language_code", type: z.string(), required: false, description: "Language code" },
    ],
  },
  {
    apiMethod: "getMyShortDescription",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_my_short_description",
    description: "Get the bot's short description.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "BotShortDescription",
    params: [
      { name: "language_code", type: z.string(), required: false, description: "Language code" },
    ],
  },
  {
    apiMethod: "setMyDefaultAdministratorRights",
    annotations: ANNOTATIONS.modify,
    toolName: "set_my_default_administrator_rights",
    description: "Set default admin rights requested when adding bot to groups/channels.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "rights", type: z.any(), required: false, description: "ChatAdministratorRights object" },
      { name: "for_channels", type: BooleanFlag, required: false, description: "For channels (default: groups)" },
    ],
  },
  {
    apiMethod: "getMyDefaultAdministratorRights",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_my_default_administrator_rights",
    description: "Get default admin rights.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "ChatAdministratorRights",
    params: [
      { name: "for_channels", type: BooleanFlag, required: false, description: "For channels (default: groups)" },
    ],
  },
  {
    apiMethod: "setMyProfilePhoto",
    annotations: ANNOTATIONS.modify,
    toolName: "set_my_profile_photo",
    description: "Set the bot's profile photo (v9.4).",
    category: "bot",
    needsChatId: false,
    canUploadFiles: true,
    returns: "true",
    params: [
      { name: "photo", type: z.any(), required: true, description: "InputProfilePhoto object" },
    ],
  },
  {
    apiMethod: "removeMyProfilePhoto",
    annotations: ANNOTATIONS.modify,
    toolName: "remove_my_profile_photo",
    description: "Remove the bot's profile photo (v9.4).",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "photo_id", type: z.string(), required: false, description: "Photo ID to remove" },
    ],
  },
  {
    apiMethod: "getUserProfilePhotos",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_user_profile_photos",
    description: "Get a user's profile photos.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "UserProfilePhotos",
    params: [
      { name: "user_id", type: z.number().int(), required: true, description: "User ID" },
      { name: "offset", type: z.number().int(), required: false, description: "Photo offset" },
      { name: "limit", type: z.number().int().min(1).max(100), required: false, description: "Max photos (1-100)" },
    ],
  },
  {
    apiMethod: "getUserProfileAudios",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_user_profile_audios",
    description: "Get a user's profile audio tracks (v9.4).",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "UserProfileAudios",
    params: [
      { name: "user_id", type: z.number().int(), required: true, description: "User ID" },
      { name: "offset", type: z.number().int(), required: false, description: "Audio offset" },
      { name: "limit", type: z.number().int().min(1).max(100), required: false, description: "Max audios (1-100)" },
    ],
  },
  {
    apiMethod: "getFile",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_file",
    description: "Get file info for downloading. Returns file_path — use https://api.telegram.org/file/bot<token>/<file_path> to download.",
    category: "bot",
    needsChatId: false,
    canUploadFiles: false,
    returns: "File",
    params: [
      { name: "file_id", type: z.string(), required: true, description: "File identifier from a message" },
    ],
  },
];
