import { z } from "zod";
import { MethodDef, ChatId, UserId, BooleanFlag, FileInput ,  ANNOTATIONS } from "../method-registry.js";

export const chatMethods: MethodDef[] = [
  // ─── Chat Info ────────────────────────────────────────────────
  {
    apiMethod: "getChat",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_chat",
    description: "Get full information about a chat (title, description, photo, member count, permissions, etc).",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "ChatFullInfo",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
    ],
  },
  {
    apiMethod: "getChatAdministrators",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_chat_administrators",
    description: "Get a list of administrators in a chat.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "Array of ChatMember",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
    ],
  },
  {
    apiMethod: "getChatMemberCount",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_chat_member_count",
    description: "Get the number of members in a chat.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "Integer",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
    ],
  },
  {
    apiMethod: "getChatMember",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_chat_member",
    description: "Get information about a member in a chat.",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "ChatMember",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID" },
    ],
  },

  // ─── Member Management ────────────────────────────────────────
  {
    apiMethod: "banChatMember",
    annotations: ANNOTATIONS.destructive,
    toolName: "ban_chat_member",
    description: "Ban a user from a chat. In supergroups/channels, the user cannot return without being unbanned.",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID to ban" },
      { name: "until_date", type: z.number().int(), required: false, description: "Unix timestamp for unban (0 or >366 days = forever)" },
      { name: "revoke_messages", type: BooleanFlag, required: false, description: "Delete all messages from the user" },
    ],
  },
  {
    apiMethod: "unbanChatMember",
    annotations: ANNOTATIONS.modify,
    toolName: "unban_chat_member",
    description: "Unban a previously banned user.",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID to unban" },
      { name: "only_if_banned", type: BooleanFlag, required: false, description: "Only unban if currently banned" },
    ],
  },
  {
    apiMethod: "restrictChatMember",
    annotations: ANNOTATIONS.modify,
    toolName: "restrict_chat_member",
    description: "Restrict a user's permissions in a supergroup.",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID" },
      { name: "permissions", type: z.any(), required: true, description: "ChatPermissions object" },
      { name: "use_independent_chat_permissions", type: BooleanFlag, required: false, description: "Use independent permissions" },
      { name: "until_date", type: z.number().int(), required: false, description: "Unix timestamp when restrictions are lifted" },
    ],
  },
  {
    apiMethod: "promoteChatMember",
    annotations: ANNOTATIONS.modify,
    toolName: "promote_chat_member",
    description: "Promote or demote a user in a supergroup or channel.",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID" },
      { name: "is_anonymous", type: BooleanFlag, required: false, description: "Admin actions are anonymous" },
      { name: "can_manage_chat", type: BooleanFlag, required: false, description: "Can manage chat" },
      { name: "can_delete_messages", type: BooleanFlag, required: false, description: "Can delete messages" },
      { name: "can_manage_video_chats", type: BooleanFlag, required: false, description: "Can manage video chats" },
      { name: "can_restrict_members", type: BooleanFlag, required: false, description: "Can restrict members" },
      { name: "can_promote_members", type: BooleanFlag, required: false, description: "Can promote members" },
      { name: "can_change_info", type: BooleanFlag, required: false, description: "Can change chat info" },
      { name: "can_invite_users", type: BooleanFlag, required: false, description: "Can invite users" },
      { name: "can_post_messages", type: BooleanFlag, required: false, description: "Can post in channels" },
      { name: "can_edit_messages", type: BooleanFlag, required: false, description: "Can edit messages in channels" },
      { name: "can_pin_messages", type: BooleanFlag, required: false, description: "Can pin messages" },
      { name: "can_manage_topics", type: BooleanFlag, required: false, description: "Can manage forum topics" },
      { name: "can_manage_tags", type: BooleanFlag, required: false, description: "Can manage member tags (v9.5)" },
      { name: "can_post_stories", type: BooleanFlag, required: false, description: "Can post stories in channels" },
      { name: "can_edit_stories", type: BooleanFlag, required: false, description: "Can edit stories in channels" },
      { name: "can_delete_stories", type: BooleanFlag, required: false, description: "Can delete stories in channels" },
      { name: "can_manage_direct_messages", type: BooleanFlag, required: false, description: "Can manage direct messages in channels" },
    ],
  },
  {
    apiMethod: "setChatAdministratorCustomTitle",
    annotations: ANNOTATIONS.modify,
    toolName: "set_chat_administrator_custom_title",
    description: "Set a custom title for an administrator.",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID" },
      { name: "custom_title", type: z.string().max(16), required: true, description: "Custom title (0-16 chars)" },
    ],
  },
  {
    apiMethod: "setChatMemberTag",
    annotations: ANNOTATIONS.modify,
    toolName: "set_chat_member_tag",
    description: "Set or remove a tag for a chat member (v9.5).",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID" },
      { name: "tag", type: z.string().max(32), required: false, description: "Member tag (0-32 chars, empty to remove)" },
    ],
  },
  {
    apiMethod: "banChatSenderChat",
    annotations: ANNOTATIONS.destructive,
    toolName: "ban_chat_sender_chat",
    description: "Ban a channel chat from sending messages in a supergroup.",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "sender_chat_id", type: z.number().int(), required: true, description: "Channel chat ID to ban" },
    ],
  },
  {
    apiMethod: "unbanChatSenderChat",
    annotations: ANNOTATIONS.modify,
    toolName: "unban_chat_sender_chat",
    description: "Unban a previously banned channel chat.",
    category: "members",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "sender_chat_id", type: z.number().int(), required: true, description: "Channel chat ID to unban" },
    ],
  },

  // ─── Chat Settings ────────────────────────────────────────────
  {
    apiMethod: "setChatPermissions",
    annotations: ANNOTATIONS.modify,
    toolName: "set_chat_permissions",
    description: "Set default permissions for all members in a group/supergroup.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "permissions", type: z.any(), required: true, description: "ChatPermissions object" },
      { name: "use_independent_chat_permissions", type: BooleanFlag, required: false, description: "Use independent permissions" },
    ],
  },
  {
    apiMethod: "setChatPhoto",
    annotations: ANNOTATIONS.modify,
    toolName: "set_chat_photo",
    description: "Set a new chat photo.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: true,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "photo", type: FileInput, required: true, description: "New chat photo" },
    ],
  },
  {
    apiMethod: "deleteChatPhoto",
    annotations: ANNOTATIONS.destructive,
    toolName: "delete_chat_photo",
    description: "Delete a chat photo.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
    ],
  },
  {
    apiMethod: "setChatTitle",
    annotations: ANNOTATIONS.modify,
    toolName: "set_chat_title",
    description: "Change the title of a chat.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "title", type: z.string().min(1).max(128), required: true, description: "New chat title (1-128 chars)" },
    ],
  },
  {
    apiMethod: "setChatDescription",
    annotations: ANNOTATIONS.modify,
    toolName: "set_chat_description",
    description: "Change the description of a chat.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "description", type: z.string().max(255), required: false, description: "New description (0-255 chars)" },
    ],
  },
  {
    apiMethod: "setChatStickerSet",
    annotations: ANNOTATIONS.modify,
    toolName: "set_chat_sticker_set",
    description: "Set the sticker set for a supergroup.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "sticker_set_name", type: z.string(), required: true, description: "Sticker set name" },
    ],
  },
  {
    apiMethod: "deleteChatStickerSet",
    annotations: ANNOTATIONS.destructive,
    toolName: "delete_chat_sticker_set",
    description: "Delete the sticker set from a supergroup.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
    ],
  },
  {
    apiMethod: "leaveChat",
    annotations: ANNOTATIONS.destructive,
    toolName: "leave_chat",
    description: "Bot leaves a group, supergroup, or channel.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
    ],
  },

  // ─── Pinning ──────────────────────────────────────────────────
  {
    apiMethod: "pinChatMessage",
    annotations: ANNOTATIONS.modify,
    toolName: "pin_chat_message",
    description: "Pin a message in a chat.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "message_id", type: z.number().int(), required: true, description: "Message ID to pin" },
      { name: "business_connection_id", type: z.string(), required: false, description: "Business connection ID" },
      { name: "disable_notification", type: BooleanFlag, required: false, description: "Pin silently" },
    ],
  },
  {
    apiMethod: "unpinChatMessage",
    annotations: ANNOTATIONS.modify,
    toolName: "unpin_chat_message",
    description: "Unpin a message in a chat.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "message_id", type: z.number().int(), required: false, description: "Message ID to unpin (unpins latest if omitted)" },
    ],
  },
  {
    apiMethod: "unpinAllChatMessages",
    annotations: ANNOTATIONS.modify,
    toolName: "unpin_all_chat_messages",
    description: "Unpin all messages in a chat.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
    ],
  },

  // ─── Invite Links ─────────────────────────────────────────────
  {
    apiMethod: "exportChatInviteLink",
    annotations: ANNOTATIONS.destructive,
    toolName: "export_chat_invite_link",
    description: "Generate a new primary invite link (revokes previous one).",
    category: "invite",
    needsChatId: true,
    canUploadFiles: false,
    returns: "String (invite link)",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
    ],
  },
  {
    apiMethod: "createChatInviteLink",
    annotations: ANNOTATIONS.send,
    toolName: "create_chat_invite_link",
    description: "Create an additional invite link.",
    category: "invite",
    needsChatId: true,
    canUploadFiles: false,
    returns: "ChatInviteLink",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "name", type: z.string().max(32), required: false, description: "Link name (0-32 chars)" },
      { name: "expire_date", type: z.number().int(), required: false, description: "Unix timestamp when link expires" },
      { name: "member_limit", type: z.number().int().min(1).max(99999), required: false, description: "Max users (1-99999)" },
      { name: "creates_join_request", type: BooleanFlag, required: false, description: "Require admin approval" },
    ],
  },
  {
    apiMethod: "editChatInviteLink",
    annotations: ANNOTATIONS.modify,
    toolName: "edit_chat_invite_link",
    description: "Edit a non-primary invite link.",
    category: "invite",
    needsChatId: true,
    canUploadFiles: false,
    returns: "ChatInviteLink",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "invite_link", type: z.string(), required: true, description: "Invite link to edit" },
      { name: "name", type: z.string().max(32), required: false, description: "Link name" },
      { name: "expire_date", type: z.number().int(), required: false, description: "Expiry timestamp" },
      { name: "member_limit", type: z.number().int().min(1).max(99999), required: false, description: "Max users" },
      { name: "creates_join_request", type: BooleanFlag, required: false, description: "Require admin approval" },
    ],
  },
  {
    annotations: ANNOTATIONS.destructive,
    apiMethod: "revokeChatInviteLink",
    toolName: "revoke_chat_invite_link",
    description: "Revoke an invite link.",
    category: "invite",
    needsChatId: true,
    canUploadFiles: false,
    returns: "ChatInviteLink",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "invite_link", type: z.string(), required: true, description: "Invite link to revoke" },
    ],
  },
  {
    apiMethod: "approveChatJoinRequest",
    annotations: ANNOTATIONS.modify,
    toolName: "approve_chat_join_request",
    description: "Approve a chat join request.",
    category: "invite",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID to approve" },
    ],
  },
  {
    apiMethod: "declineChatJoinRequest",
    annotations: ANNOTATIONS.modify,
    toolName: "decline_chat_join_request",
    description: "Decline a chat join request.",
    category: "invite",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "user_id", type: UserId, required: true, description: "User ID to decline" },
    ],
  },

  // ─── Boosts ───────────────────────────────────────────────────
  {
    apiMethod: "getUserChatBoosts",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_user_chat_boosts",
    description: "Get a user's boosts in a chat.",
    category: "chat",
    needsChatId: true,
    canUploadFiles: false,
    returns: "UserChatBoosts",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "user_id", type: UserId, required: true, description: "User ID" },
    ],
  },
];
