import { z } from "zod";
import { MethodDef, ChatId, Text, ParseMode, MessageEntities, LinkPreviewOptions, commonEditParams, BooleanFlag ,  ANNOTATIONS } from "../method-registry.js";

export const editingMethods: MethodDef[] = [
  {
    apiMethod: "editMessageText",
    annotations: ANNOTATIONS.modify,
    toolName: "edit_message_text",
    description: "Edit the text of a message sent by the bot or via inline mode.",
    category: "editing",
    needsChatId: false,
    canUploadFiles: false,
    returns: "Message or true",
    params: [
      ...commonEditParams(),
      { name: "text", type: Text, required: true, description: "New message text (1-4096 chars)" },
      { name: "parse_mode", type: ParseMode, required: false, description: "Text formatting mode" },
      { name: "entities", type: MessageEntities, required: false, description: "Special entities" },
      { name: "link_preview_options", type: LinkPreviewOptions, required: false, description: "Link preview settings" },
    ],
  },
  {
    apiMethod: "editMessageCaption",
    annotations: ANNOTATIONS.modify,
    toolName: "edit_message_caption",
    description: "Edit the caption of a media message.",
    category: "editing",
    needsChatId: false,
    canUploadFiles: false,
    returns: "Message or true",
    params: [
      ...commonEditParams(),
      { name: "caption", type: z.string().max(1024), required: false, description: "New caption (0-1024 chars)" },
      { name: "parse_mode", type: ParseMode, required: false, description: "Caption formatting mode" },
      { name: "caption_entities", type: MessageEntities, required: false, description: "Caption entities" },
      { name: "show_caption_above_media", type: BooleanFlag, required: false, description: "Show caption above media" },
    ],
  },
  {
    apiMethod: "editMessageMedia",
    annotations: ANNOTATIONS.modify,
    toolName: "edit_message_media",
    description: "Edit the media content of a message (photo, video, animation, document, audio).",
    category: "editing",
    needsChatId: false,
    canUploadFiles: true,
    returns: "Message or true",
    params: [
      ...commonEditParams(),
      { name: "media", type: z.any(), required: true, description: "New InputMedia object" },
    ],
  },
  {
    apiMethod: "editMessageReplyMarkup",
    annotations: ANNOTATIONS.modify,
    toolName: "edit_message_reply_markup",
    description: "Edit the inline keyboard of a message.",
    category: "editing",
    needsChatId: false,
    canUploadFiles: false,
    returns: "Message or true",
    params: commonEditParams(),
  },
  {
    apiMethod: "editMessageLiveLocation",
    annotations: ANNOTATIONS.modify,
    toolName: "edit_message_live_location",
    description: "Edit a live location message.",
    category: "editing",
    needsChatId: false,
    canUploadFiles: false,
    returns: "Message or true",
    params: [
      ...commonEditParams(),
      { name: "latitude", type: z.number(), required: true, description: "New latitude" },
      { name: "longitude", type: z.number(), required: true, description: "New longitude" },
      { name: "horizontal_accuracy", type: z.number().min(0).max(1500), required: false, description: "Uncertainty radius" },
      { name: "heading", type: z.number().int().min(1).max(360), required: false, description: "Direction in degrees" },
      { name: "proximity_alert_radius", type: z.number().int(), required: false, description: "Proximity alert distance" },
    ],
  },
  {
    apiMethod: "stopMessageLiveLocation",
    annotations: ANNOTATIONS.modify,
    toolName: "stop_message_live_location",
    description: "Stop updating a live location message.",
    category: "editing",
    needsChatId: false,
    canUploadFiles: false,
    returns: "Message or true",
    params: commonEditParams(),
  },
  {
    apiMethod: "editMessageChecklist",
    annotations: ANNOTATIONS.modify,
    toolName: "edit_message_checklist",
    description: "Edit a checklist message (v9.1).",
    category: "editing",
    needsChatId: true,
    canUploadFiles: false,
    returns: "Message or true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_id", type: z.number().int(), required: true, description: "Message ID" },
      { name: "checklist", type: z.any(), required: true, description: "New InputChecklist object" },
      { name: "reply_markup", type: z.any(), required: false, description: "Inline keyboard markup" },
    ],
  },
  {
    apiMethod: "deleteMessage",
    annotations: ANNOTATIONS.destructive,
    toolName: "delete_message",
    description: "Delete a message. Bot must have delete rights in the chat.",
    category: "editing",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_id", type: z.number().int(), required: true, description: "Message ID to delete" },
    ],
  },
  {
    apiMethod: "deleteMessages",
    annotations: ANNOTATIONS.destructive,
    toolName: "delete_messages",
    description: "Delete multiple messages at once. Max 100 messages.",
    category: "editing",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_ids", type: z.array(z.number().int()).min(1).max(100), required: true, description: "Message IDs to delete (1-100)" },
    ],
  },
  {
    apiMethod: "stopPoll",
    annotations: ANNOTATIONS.modify,
    toolName: "stop_poll",
    description: "Stop a poll in a chat.",
    category: "editing",
    needsChatId: true,
    canUploadFiles: false,
    returns: "Poll",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_id", type: z.number().int(), required: true, description: "Poll message ID" },
      { name: "business_connection_id", type: z.string(), required: false, description: "Business connection ID" },
      { name: "reply_markup", type: z.any(), required: false, description: "Inline keyboard markup" },
    ],
  },
];
