import { z } from "zod";
import { MethodDef, ChatId } from "../method-registry.js";

const ThreadId = z.number().int().describe("Forum topic thread ID");

export const forumMethods: MethodDef[] = [
  {
    apiMethod: "getForumTopicIconStickers",
    toolName: "get_forum_topic_icon_stickers",
    description: "Get custom emoji stickers that can be used as forum topic icons.",
    category: "forum",
    needsChatId: false,
    canUploadFiles: false,
    returns: "Array of Sticker",
    params: [],
  },
  {
    apiMethod: "createForumTopic",
    toolName: "create_forum_topic",
    description: "Create a topic in a forum supergroup or private chat (v9.4+).",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "ForumTopic",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID or @username" },
      { name: "name", type: z.string().min(1).max(128), required: true, description: "Topic name (1-128 chars)" },
      { name: "icon_color", type: z.number().int(), required: false, description: "Icon color in RGB" },
      { name: "icon_custom_emoji_id", type: z.string(), required: false, description: "Custom emoji ID for icon" },
    ],
  },
  {
    apiMethod: "editForumTopic",
    toolName: "edit_forum_topic",
    description: "Edit name and icon of a forum topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_thread_id", type: ThreadId, required: true, description: "Topic thread ID" },
      { name: "name", type: z.string().min(1).max(128), required: false, description: "New topic name" },
      { name: "icon_custom_emoji_id", type: z.string(), required: false, description: "New custom emoji icon" },
    ],
  },
  {
    apiMethod: "closeForumTopic",
    toolName: "close_forum_topic",
    description: "Close an open topic in a forum supergroup.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_thread_id", type: ThreadId, required: true, description: "Topic thread ID" },
    ],
  },
  {
    apiMethod: "reopenForumTopic",
    toolName: "reopen_forum_topic",
    description: "Reopen a closed topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_thread_id", type: ThreadId, required: true, description: "Topic thread ID" },
    ],
  },
  {
    apiMethod: "deleteForumTopic",
    toolName: "delete_forum_topic",
    description: "Delete a forum topic along with all its messages.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_thread_id", type: ThreadId, required: true, description: "Topic thread ID" },
    ],
  },
  {
    apiMethod: "unpinAllForumTopicMessages",
    toolName: "unpin_all_forum_topic_messages",
    description: "Unpin all messages in a forum topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "message_thread_id", type: ThreadId, required: true, description: "Topic thread ID" },
    ],
  },
  {
    apiMethod: "editGeneralForumTopic",
    toolName: "edit_general_forum_topic",
    description: "Edit the name of the 'General' forum topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
      { name: "name", type: z.string().min(1).max(128), required: true, description: "New name" },
    ],
  },
  {
    apiMethod: "closeGeneralForumTopic",
    toolName: "close_general_forum_topic",
    description: "Close the 'General' topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
    ],
  },
  {
    apiMethod: "reopenGeneralForumTopic",
    toolName: "reopen_general_forum_topic",
    description: "Reopen the 'General' topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
    ],
  },
  {
    apiMethod: "hideGeneralForumTopic",
    toolName: "hide_general_forum_topic",
    description: "Hide the 'General' topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
    ],
  },
  {
    apiMethod: "unhideGeneralForumTopic",
    toolName: "unhide_general_forum_topic",
    description: "Unhide the 'General' topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
    ],
  },
  {
    apiMethod: "unpinAllGeneralForumTopicMessages",
    toolName: "unpin_all_general_forum_topic_messages",
    description: "Unpin all messages in the 'General' topic.",
    category: "forum",
    needsChatId: true,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Chat ID" },
    ],
  },
];
