import { z } from "zod";
import { MethodDef, ChatId, BooleanFlag } from "../method-registry.js";

export const forwardingMethods: MethodDef[] = [
  {
    apiMethod: "forwardMessage",
    toolName: "forward_message",
    description: "Forward a message from one chat to another.",
    category: "forwarding",
    needsChatId: true,
    canUploadFiles: false,
    returns: "Message",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Target chat ID" },
      { name: "from_chat_id", type: ChatId, required: true, description: "Source chat ID" },
      { name: "message_id", type: z.number().int(), required: true, description: "Message ID to forward" },
      { name: "message_thread_id", type: z.number().int(), required: false, description: "Forum topic thread ID" },
      { name: "disable_notification", type: BooleanFlag, required: false, description: "Send silently" },
      { name: "protect_content", type: BooleanFlag, required: false, description: "Protect from forwarding" },
    ],
  },
  {
    apiMethod: "forwardMessages",
    toolName: "forward_messages",
    description: "Forward multiple messages at once (maintains album grouping).",
    category: "forwarding",
    needsChatId: true,
    canUploadFiles: false,
    returns: "Array of MessageId",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Target chat ID" },
      { name: "from_chat_id", type: ChatId, required: true, description: "Source chat ID" },
      { name: "message_ids", type: z.array(z.number().int()), required: true, description: "Message IDs to forward" },
      { name: "message_thread_id", type: z.number().int(), required: false, description: "Forum topic thread ID" },
      { name: "disable_notification", type: BooleanFlag, required: false, description: "Send silently" },
      { name: "protect_content", type: BooleanFlag, required: false, description: "Protect from forwarding" },
    ],
  },
  {
    apiMethod: "copyMessage",
    toolName: "copy_message",
    description: "Copy a message (sends without 'Forwarded from' header). Can change caption.",
    category: "forwarding",
    needsChatId: true,
    canUploadFiles: false,
    returns: "MessageId",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Target chat ID" },
      { name: "from_chat_id", type: ChatId, required: true, description: "Source chat ID" },
      { name: "message_id", type: z.number().int(), required: true, description: "Message ID to copy" },
      { name: "message_thread_id", type: z.number().int(), required: false, description: "Forum topic thread ID" },
      { name: "caption", type: z.string().max(1024), required: false, description: "New caption" },
      { name: "parse_mode", type: z.enum(["HTML", "Markdown", "MarkdownV2"]), required: false, description: "Caption formatting" },
      { name: "caption_entities", type: z.any(), required: false, description: "Caption entities" },
      { name: "show_caption_above_media", type: BooleanFlag, required: false, description: "Show caption above media" },
      { name: "reply_parameters", type: z.any(), required: false, description: "Reply settings" },
      { name: "reply_markup", type: z.any(), required: false, description: "Keyboard markup" },
      { name: "disable_notification", type: BooleanFlag, required: false, description: "Send silently" },
      { name: "protect_content", type: BooleanFlag, required: false, description: "Protect from forwarding" },
    ],
  },
  {
    apiMethod: "copyMessages",
    toolName: "copy_messages",
    description: "Copy multiple messages at once.",
    category: "forwarding",
    needsChatId: true,
    canUploadFiles: false,
    returns: "Array of MessageId",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Target chat ID" },
      { name: "from_chat_id", type: ChatId, required: true, description: "Source chat ID" },
      { name: "message_ids", type: z.array(z.number().int()), required: true, description: "Message IDs to copy" },
      { name: "message_thread_id", type: z.number().int(), required: false, description: "Forum topic thread ID" },
      { name: "disable_notification", type: BooleanFlag, required: false, description: "Send silently" },
      { name: "protect_content", type: BooleanFlag, required: false, description: "Protect from forwarding" },
      { name: "remove_caption", type: BooleanFlag, required: false, description: "Remove captions" },
    ],
  },
];
