import { z } from "zod";
import { MethodDef, ChatId, BooleanFlag, commonSendParams ,  ANNOTATIONS } from "../method-registry.js";

export const paymentMethods: MethodDef[] = [
  {
    apiMethod: "sendInvoice",
    annotations: ANNOTATIONS.send,
    toolName: "send_invoice",
    description: "Send an invoice for payment.",
    category: "payments",
    needsChatId: true,
    canUploadFiles: false,
    returns: "Message",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Target chat ID" },
      { name: "title", type: z.string(), required: true, description: "Product name" },
      { name: "description", type: z.string(), required: true, description: "Product description" },
      { name: "payload", type: z.string(), required: true, description: "Bot-defined invoice payload" },
      { name: "currency", type: z.string(), required: true, description: "ISO 4217 currency code" },
      { name: "prices", type: z.any(), required: true, description: "Array of LabeledPrice" },
      { name: "provider_token", type: z.string(), required: false, description: "Payment provider token" },
      { name: "max_tip_amount", type: z.number().int(), required: false, description: "Max tip amount in smallest units" },
      { name: "suggested_tip_amounts", type: z.array(z.number().int()), required: false, description: "Suggested tip amounts" },
      { name: "start_parameter", type: z.string(), required: false, description: "Deep-linking start parameter" },
      { name: "photo_url", type: z.string(), required: false, description: "Product photo URL" },
      { name: "photo_size", type: z.number().int(), required: false, description: "Photo size in bytes" },
      { name: "photo_width", type: z.number().int(), required: false, description: "Photo width" },
      { name: "photo_height", type: z.number().int(), required: false, description: "Photo height" },
      { name: "need_name", type: BooleanFlag, required: false, description: "Request user's full name" },
      { name: "need_phone_number", type: BooleanFlag, required: false, description: "Request phone number" },
      { name: "need_email", type: BooleanFlag, required: false, description: "Request email" },
      { name: "need_shipping_address", type: BooleanFlag, required: false, description: "Request shipping address" },
      { name: "send_phone_number_to_provider", type: BooleanFlag, required: false, description: "Send phone to provider" },
      { name: "send_email_to_provider", type: BooleanFlag, required: false, description: "Send email to provider" },
      { name: "is_flexible", type: BooleanFlag, required: false, description: "Price depends on shipping" },
      ...commonSendParams(),
    ],
  },
  {
    apiMethod: "createInvoiceLink",
    annotations: ANNOTATIONS.send,
    toolName: "create_invoice_link",
    description: "Create a link for an invoice.",
    category: "payments",
    needsChatId: false,
    canUploadFiles: false,
    returns: "String (URL)",
    params: [
      { name: "title", type: z.string(), required: true, description: "Product name" },
      { name: "description", type: z.string(), required: true, description: "Product description" },
      { name: "payload", type: z.string(), required: true, description: "Bot-defined payload" },
      { name: "currency", type: z.string(), required: true, description: "ISO 4217 currency code" },
      { name: "prices", type: z.any(), required: true, description: "Array of LabeledPrice" },
      { name: "provider_token", type: z.string(), required: false, description: "Payment provider token" },
    ],
  },
  {
    apiMethod: "answerShippingQuery",
    annotations: ANNOTATIONS.send,
    toolName: "answer_shipping_query",
    description: "Reply to shipping queries. Called if sendInvoice used is_flexible.",
    category: "payments",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "shipping_query_id", type: z.string(), required: true, description: "Shipping query ID" },
      { name: "ok", type: BooleanFlag, required: true, description: "Delivery possible?" },
      { name: "shipping_options", type: z.any(), required: false, description: "Array of ShippingOption" },
      { name: "error_message", type: z.string(), required: false, description: "Error message if ok=false" },
    ],
  },
  {
    apiMethod: "answerPreCheckoutQuery",
    annotations: ANNOTATIONS.send,
    toolName: "answer_pre_checkout_query",
    description: "Respond to pre-checkout queries. Must answer within 10 seconds.",
    category: "payments",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "pre_checkout_query_id", type: z.string(), required: true, description: "Pre-checkout query ID" },
      { name: "ok", type: BooleanFlag, required: true, description: "Allow checkout?" },
      { name: "error_message", type: z.string(), required: false, description: "Error message if ok=false" },
    ],
  },
  {
    apiMethod: "getStarTransactions",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_star_transactions",
    description: "Get the bot's Telegram Star transactions.",
    category: "payments",
    needsChatId: false,
    canUploadFiles: false,
    returns: "StarTransactions",
    params: [
      { name: "offset", type: z.number().int(), required: false, description: "Offset" },
      { name: "limit", type: z.number().int().min(1).max(100), required: false, description: "Max transactions (1-100)" },
    ],
  },
  {
    apiMethod: "getMyStarBalance",
    annotations: ANNOTATIONS.readOnly,
    toolName: "get_my_star_balance",
    description: "Get the bot's Telegram Stars balance (v9.1).",
    category: "payments",
    needsChatId: false,
    canUploadFiles: false,
    returns: "StarAmount",
    params: [],
  },
  {
    annotations: ANNOTATIONS.modify,
    apiMethod: "refundStarPayment",
    toolName: "refund_star_payment",
    description: "Refund a Telegram Star payment.",
    category: "payments",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "user_id", type: z.number().int(), required: true, description: "User ID" },
      { name: "telegram_payment_charge_id", type: z.string(), required: true, description: "Telegram payment charge ID" },
    ],
  },
];
