import { z } from "zod";
import { MethodDef, ChatId, FileInput, BooleanFlag, commonSendParams } from "../method-registry.js";

export const stickerMethods: MethodDef[] = [
  {
    apiMethod: "sendSticker",
    toolName: "send_sticker",
    description: "Send a sticker.",
    category: "stickers",
    needsChatId: true,
    canUploadFiles: true,
    returns: "Message",
    params: [
      { name: "chat_id", type: ChatId, required: true, description: "Target chat ID" },
      { name: "sticker", type: FileInput, required: true, description: "Sticker to send (file_id, URL, or path)" },
      { name: "emoji", type: z.string(), required: false, description: "Associated emoji" },
      ...commonSendParams(),
    ],
  },
  {
    apiMethod: "getStickerSet",
    toolName: "get_sticker_set",
    description: "Get a sticker set by name.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "StickerSet",
    params: [
      { name: "name", type: z.string(), required: true, description: "Sticker set name" },
    ],
  },
  {
    apiMethod: "getCustomEmojiStickers",
    toolName: "get_custom_emoji_stickers",
    description: "Get information about custom emoji stickers by their identifiers.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "Array of Sticker",
    params: [
      { name: "custom_emoji_ids", type: z.array(z.string()), required: true, description: "Custom emoji IDs" },
    ],
  },
  {
    apiMethod: "uploadStickerFile",
    toolName: "upload_sticker_file",
    description: "Upload a sticker file to Telegram for later use in createNewStickerSet.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: true,
    returns: "File",
    params: [
      { name: "user_id", type: z.number().int(), required: true, description: "User ID of sticker set owner" },
      { name: "sticker", type: FileInput, required: true, description: "Sticker file" },
      { name: "sticker_format", type: z.enum(["static", "animated", "video"]), required: true, description: "Sticker format" },
    ],
  },
  {
    apiMethod: "createNewStickerSet",
    toolName: "create_new_sticker_set",
    description: "Create a new sticker set owned by a user.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "StickerSet",
    params: [
      { name: "user_id", type: z.number().int(), required: true, description: "User ID of sticker set owner" },
      { name: "name", type: z.string(), required: true, description: "Short name (e.g. animals_by_bot)" },
      { name: "title", type: z.string(), required: true, description: "Sticker set title" },
      { name: "stickers", type: z.any(), required: true, description: "Array of InputSticker objects" },
      { name: "sticker_type", type: z.enum(["regular", "mask", "custom_emoji"]), required: false, description: "Sticker type" },
      { name: "needs_repainting", type: BooleanFlag, required: false, description: "Allow repainting" },
    ],
  },
  {
    apiMethod: "addStickerToSet",
    toolName: "add_sticker_to_set",
    description: "Add a sticker to an existing set.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "user_id", type: z.number().int(), required: true, description: "User ID of set owner" },
      { name: "name", type: z.string(), required: true, description: "Sticker set name" },
      { name: "sticker", type: z.any(), required: true, description: "InputSticker object" },
    ],
  },
  {
    apiMethod: "setStickerPositionInSet",
    toolName: "set_sticker_position_in_set",
    description: "Move a sticker to a specific position in the set.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "sticker", type: z.string(), required: true, description: "Sticker file_id" },
      { name: "position", type: z.number().int().min(0), required: true, description: "New position (0-based)" },
    ],
  },
  {
    apiMethod: "deleteStickerFromSet",
    toolName: "delete_sticker_from_set",
    description: "Delete a sticker from a set.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "sticker", type: z.string(), required: true, description: "Sticker file_id" },
    ],
  },
  {
    apiMethod: "replaceStickerInSet",
    toolName: "replace_sticker_in_set",
    description: "Replace an existing sticker in a set with a new one.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "user_id", type: z.number().int(), required: true, description: "User ID of set owner" },
      { name: "name", type: z.string(), required: true, description: "Sticker set name" },
      { name: "old_sticker", type: z.string(), required: true, description: "file_id of sticker to replace" },
      { name: "sticker", type: z.any(), required: true, description: "New InputSticker object" },
    ],
  },
  {
    apiMethod: "setStickerSetTitle",
    toolName: "set_sticker_set_title",
    description: "Set the title of a sticker set.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "name", type: z.string(), required: true, description: "Sticker set name" },
      { name: "title", type: z.string(), required: true, description: "New title" },
    ],
  },
  {
    apiMethod: "setStickerSetThumbnail",
    toolName: "set_sticker_set_thumbnail",
    description: "Set the thumbnail of a sticker set.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: true,
    returns: "true",
    params: [
      { name: "name", type: z.string(), required: true, description: "Sticker set name" },
      { name: "user_id", type: z.number().int(), required: true, description: "User ID of set owner" },
      { name: "thumbnail", type: FileInput, required: false, description: "Thumbnail file" },
    ],
  },
  {
    apiMethod: "setCustomEmojiStickerSetThumbnail",
    toolName: "set_custom_emoji_sticker_set_thumbnail",
    description: "Set the thumbnail of a custom emoji sticker set.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "name", type: z.string(), required: true, description: "Sticker set name" },
      { name: "custom_emoji_id", type: z.string(), required: false, description: "Custom emoji ID for thumbnail" },
    ],
  },
  {
    apiMethod: "setStickerEmojiList",
    toolName: "set_sticker_emoji_list",
    description: "Change the list of emoji associated with a sticker.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "sticker", type: z.string(), required: true, description: "Sticker file_id" },
      { name: "emoji_list", type: z.array(z.string()), required: true, description: "Array of emoji" },
    ],
  },
  {
    apiMethod: "deleteStickerSet",
    toolName: "delete_sticker_set",
    description: "Delete a sticker set created by the bot.",
    category: "stickers",
    needsChatId: false,
    canUploadFiles: false,
    returns: "true",
    params: [
      { name: "name", type: z.string(), required: true, description: "Sticker set name" },
    ],
  },
];
