#!/usr/bin/env node
/**
 * Refresh the local mirror of the Telegram Bot API docs.
 *
 *   node scripts/refresh-docs.mjs
 *
 * Downloads every core.telegram.org/bots/* page into docs/ and regenerates the
 * derived artifacts the registry is audited against:
 *   - official-method-list.txt / official-type-list.txt
 *   - api-params.json  (per-method parameter tables, machine readable)
 *   - bot-api-methods.md (human readable)
 *   - api-version.txt
 *
 * Run `node scripts/audit-registry.mjs` afterwards to diff src/methods against it.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseBotApi, uploadSchemaSource } from "./bot-api-spec.mjs";

const DOCS = join(dirname(fileURLToPath(import.meta.url)), "..", "docs");
const PAGES = ["api", "api-changelog", "features", "faq", "inline", "webhooks", "webapps", "payments", "games"];

mkdirSync(DOCS, { recursive: true });

const pages = {};
for (const page of PAGES) {
  const res = await fetch(`https://core.telegram.org/bots/${page}`, { signal: AbortSignal.timeout(30000) });
  if (!res.ok) throw new Error(`GET /bots/${page} → ${res.status}`);
  const html = await res.text();
  pages[page] = html;
  writeFileSync(join(DOCS, `raw-${page}.html`), html);
  console.log(`${page.padEnd(14)} ${html.length} bytes`);
}

const api = pages.api;

// ─── Version (first "Bot API X.Y" heading in the changelog) ──────────────
const version = /Bot API (\d+\.\d+)/.exec(pages["api-changelog"])?.[1] ?? "unknown";
writeFileSync(join(DOCS, "api-version.txt"), `${version}\n`);

const spec = parseBotApi(api);
const methods = spec.methods;
const types = Object.keys(spec.types);
writeFileSync(join(DOCS, "api-types.json"), JSON.stringify(spec.types, null, 1) + "\n");
writeFileSync(join(DOCS, "../src/upload-schema.ts"), uploadSchemaSource(spec));

const methodNames = Object.keys(methods).sort();
const typeNames = [...new Set(types)].sort();

writeFileSync(join(DOCS, "official-method-list.txt"), methodNames.join("\n") + "\n");
writeFileSync(join(DOCS, "official-type-list.txt"), typeNames.join("\n") + "\n");
writeFileSync(join(DOCS, "api-params.json"), JSON.stringify(methods, null, 1));

const md = [
  `# Telegram Bot API ${version} — methods`,
  ``,
  `${methodNames.length} methods, ${typeNames.length} types. Generated by scripts/refresh-docs.mjs.`,
  ``,
  ...methodNames.flatMap((m) => [
    `## ${m}`,
    methods[m].description,
    ``,
    ...(methods[m].params.length
      ? methods[m].params.map((p) => `- \`${p.name}\` — ${p.type}${p.required ? " **(required)**" : ""}`)
      : ["_No parameters._"]),
    ``,
  ]),
].join("\n");
writeFileSync(join(DOCS, "bot-api-methods.md"), md);

console.log(`\nBot API ${version}: ${methodNames.length} methods, ${typeNames.length} types`);
