#!/usr/bin/env node
/**
 * Refresh the local mirror of the Telegram Bot API docs.
 *
 *   node scripts/refresh-docs.mjs
 *
 * Downloads every core.telegram.org/bots/* page into docs/ and regenerates the
 * derived artifacts the registry is audited against:
 *   - official-method-list.txt / official-type-list.txt
 *   - api-params.json  (per-method parameter tables, machine readable)
 *   - bot-api-methods.md (human readable)
 *   - api-version.txt
 *
 * Run `node scripts/audit-registry.mjs` afterwards to diff src/methods against it.
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DOCS = join(dirname(fileURLToPath(import.meta.url)), "..", "docs");
const PAGES = ["api", "api-changelog", "features", "faq", "inline", "webhooks", "webapps", "payments", "games"];

const decode = (s) =>
  s
    .replace(/&#8212;/g, "—")
    .replace(/&#8230;/g, "…")
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&");

const text = (s) => decode(s.replace(/<[^>]+>/g, "")).replace(/\s+/g, " ").trim();

mkdirSync(DOCS, { recursive: true });

const pages = {};
for (const page of PAGES) {
  const res = await fetch(`https://core.telegram.org/bots/${page}`);
  if (!res.ok) throw new Error(`GET /bots/${page} → ${res.status}`);
  const html = await res.text();
  pages[page] = html;
  writeFileSync(join(DOCS, `raw-${page}.html`), html);
  console.log(`${page.padEnd(14)} ${html.length} bytes`);
}

const api = pages.api;

// ─── Version (first "Bot API X.Y" heading in the changelog) ──────────────
const version = /Bot API (\d+\.\d+)/.exec(pages["api-changelog"])?.[1] ?? "unknown";
writeFileSync(join(DOCS, "api-version.txt"), `${version}\n`);

// ─── Methods, types and their parameter tables ───────────────────────────
// Every method/type on the page is an <h4> anchor; methods start lowercase,
// types uppercase. The <table class="table"> that follows holds the params.
const methods = {};
const types = [];

for (const chunk of api.split(/<h4>/).slice(1)) {
  const name = /^(?:<a class="anchor"[^>]*>(?:<i[^>]*><\/i>)?<\/a>)?([A-Za-z0-9]+)<\/h4>/.exec(chunk)?.[1];
  if (!name) continue;
  if (/^[A-Z]/.test(name)) {
    types.push(name);
    continue;
  }
  const table = /<table class="table">([\s\S]*?)<\/table>/.exec(chunk);
  const rows = table
    ? [...table[1].matchAll(/<tr>\s*<td>([\s\S]*?)<\/td>\s*<td>([\s\S]*?)<\/td>\s*<td>([\s\S]*?)<\/td>\s*(?:<td>([\s\S]*?)<\/td>)?/g)]
    : [];
  methods[name] = {
    description: text(/<p>([\s\S]*?)<\/p>/.exec(chunk)?.[1] ?? ""),
    params: rows.map((r) => ({
      name: text(r[1]),
      type: text(r[2]),
      required: text(r[3]) === "Yes",
      description: text(r[4] ?? ""),
    })),
  };
}

const methodNames = Object.keys(methods).sort();
const typeNames = [...new Set(types)].sort();

writeFileSync(join(DOCS, "official-method-list.txt"), methodNames.join("\n") + "\n");
writeFileSync(join(DOCS, "official-type-list.txt"), typeNames.join("\n") + "\n");
writeFileSync(join(DOCS, "api-params.json"), JSON.stringify(methods, null, 1));

const md = [
  `# Telegram Bot API ${version} — methods`,
  ``,
  `${methodNames.length} methods, ${typeNames.length} types. Generated by scripts/refresh-docs.mjs.`,
  ``,
  ...methodNames.flatMap((m) => [
    `## ${m}`,
    methods[m].description,
    ``,
    ...(methods[m].params.length
      ? methods[m].params.map((p) => `- \`${p.name}\` — ${p.type}${p.required ? " **(required)**" : ""}`)
      : ["_No parameters._"]),
    ``,
  ]),
].join("\n");
writeFileSync(join(DOCS, "bot-api-methods.md"), md);

console.log(`\nBot API ${version}: ${methodNames.length} methods, ${typeNames.length} types`);
